using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace RaptureApi.Migrations
{
    public partial class RaptureData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Raptures",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    StartDate = table.Column<DateTime>(type: "datetime", nullable: false),
                    EndDate = table.Column<DateTime>(type: "datetime", nullable: false),
                    Predictor = table.Column<string>(type: "nvarchar(500)", nullable: false),
                    Details = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WhoGotRaptured = table.Column<string>(type: "nvarchar(500)", nullable: true, defaultValue: ""),
                    MonthOnly = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    YearOnly = table.Column<bool>(type: "bit", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Raptures", x => x.ID);
                });

            migrationBuilder.InsertData(
                table: "Raptures",
                columns: new[] { "ID", "Details", "MonthOnly", "Predictor", "EndDate", "StartDate", "WhoGotRaptured", "YearOnly" },
                values: new object[,]
                {
                    { 1, "Predicted the world would end this year", false, "Tynnetta Muhammad", new DateTime(2001, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2001, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", true },
                    { 76, "The world ends with the arrival of 16 million space ships and a host of angels.", false, "Sheldan Nidle", new DateTime(1996, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1996, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 75, "Camping's fourth rapture prediction, following the failure of his previous three.", false, "Harold Camping", new DateTime(1995, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1995, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 74, "Camping's third rapture prediction, following the failure of his previous two.", false, "Harold Camping", new DateTime(1994, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1994, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 73, "Camping's next rapture predicting, following the failure of his first.", false, "Harold Camping", new DateTime(1994, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1994, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 72, "Camping predicted the rapture would take place.", false, "Harold Camping", new DateTime(1994, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1994, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 71, "New York City would be destroyed by a nuclear bomb on the 23rd of March 1994, with the Battle of Armageddon taking place on the 2nd of May 1994.", false, "Neal Chase", new DateTime(1994, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1994, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 70, "The Second Coming takes place this year", false, "David Berg", new DateTime(1993, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1993, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 69, "The rapture occurs on this day", false, "Lee Jang Rim", new DateTime(1992, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1992, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 68, "The rapture begins", false, "Rollen Stewart", new DateTime(1992, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1992, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 67, "The Gulf War would be the War of Armageddon which is the final war", false, "Louis Farrakhan", new DateTime(1991, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1991, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 77, "A spacecraft was trailing the Hale-Bopp comet and suicide was the only way to evacuate Earth the souls could board the spacecraft and be taken to a level of exitence above human.", false, "Marshall Applewhite", new DateTime(1997, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1997, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), "38 of Applewhite's followers commited suicide. It's unknown as to whether or not their souls reached the spacecraft.", false },
                    { 66, "The Messiah would arrive at the start of the Jewish New Year", false, "Menachem Mendel Schneerson", new DateTime(1991, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1991, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 64, "Whisenant's revised prediction of the rapture of the Christian Church, following the failed September prediction.", false, "Edgar C. Whisenant", new DateTime(1988, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1988, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 63, "Rapture of the Christian Church.", false, "Edgar C. Whisenant", new DateTime(1988, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1988, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 62, "Predicted that Halley's Comet would be pulled into Earth's orbit.", false, "Leland Jensen", new DateTime(1986, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1986, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 61, "Predicted the world ends in 1985.", false, "Lester Sumrall", new DateTime(1985, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1985, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 60, "Predicted the world would end this year on his 700 Club TV programme.", false, "Pat Robertson", new DateTime(1982, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1982, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 59, "Placed advertisements in the Los Angeles Times stating that the second coming would occur in June with the Maitreya (World Teacher) announcing it on worldwide TV.", false, "Benjamin Creme", new DateTime(1982, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1982, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 58, "Declared \"Christ is now here!\" in newspaper advertisements and claimed he would make himself known \"within the next two months \"", true, "Tara Centers", new DateTime(1982, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1982, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 57, "Believed the gravitational force of the aligned planets would cause a number of catastrophes, including earthquakes across the San Andreas Fault.", false, "John Gribbin, Stephen Plagemann", new DateTime(1982, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1982, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 56, "The generation of 1948 is the last generation and the world ends in 1981.", false, "Chuck Smith", new DateTime(1981, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1981, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 55, "Nuclear disaster, followed by two decades of conflict culminating in God's Kingdom being established on Earth.", false, "Leland Jensen", new DateTime(1980, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1980, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 65, "A nuclear war starts on this day and lasts for 12 years.", false, "Elizabeth Clare Prophet", new DateTime(1990, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1990, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 54, "Led a commune into the Quebec wilderness to form a new society during God's 1000 year reign followed by Armageddon.", false, "Roch Thériault", new DateTime(1979, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1979, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 78, "This date is 6000 years since the creation, and therefore the end of the world.", false, "James Ussher", new DateTime(1997, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1997, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 80, "A King of Terror would come from the sky in \"1999 and seven months\".", true, "Nostradamus", new DateTime(1999, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1999, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 102, "The birth date of the Antichrist and the end of the universe.", false, "Aggai", new DateTime(1997, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1997, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 101, "Whisenant's revised prediction of the rapture of the Christian Church, following failure of his two previous predictions.", false, "Edgar C. Whisenant", new DateTime(1989, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1989, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 100, "Armageddon would heppen unless 144,000 people gathered in specifc places on Earth and meditated at the same time, which became known as Harmonic Convergence.", false, "José Argüelles", new DateTime(1987, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1987, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 99, "Christ's 1000 year reign would begin in the year 2000", false, "Jonathan Edwards", new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 98, "Predicted the end of the world in his book \"I Predict 2000\"", false, "Lester Sumrall", new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 97, "Predicted the end of the world in his book \"The End: Why Jesus Could Return by A.D. 2000\"", false, "Ed Dobson", new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 96, "The Kingdom of Heaven would be established in 2000", false, "Sun Myung Moon", new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 95, "The Second Coming would occur in the year 2000", false, "Edgar Cayce", new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 94, "The Earth's axis would shift and the Antichrist would reveal himself", false, "Ruth Montgomery", new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 93, "The planetary lineup would cause a \"star holocaust\", pulling all the planets into the sun.", false, "Nuwaubian Nation", new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 79, "God will arrive at Earth at 10am on this date in a flying saucer.", false, "Hon-Ming Chen", new DateTime(1998, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1998, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 92, "The Second Coming of Christ occurs on this day", false, "James Harmston", new DateTime(2000, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 90, "The Y2K bug would trigger global economic chaos, causing the Antichrist to rise to power. They changed their minds about this prediction as the date drew closer.", false, "Tim LaHaye & Jerry B. Jenkins", new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 89, "God pours his judgment upon the world", false, "Jerry Falwell", new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 88, "Apocalypse", false, "Movement for the Restoration of the Ten Commandments of God", new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody, but 778 followers of this movement died in a fire and a series of poisonings and killings, either as a form of group suicide or orchestrated mass murder by the group leaders after the failed prediction.", false },
                    { 87, "The last judgment would occur before 2000.", false, "Nazim Al-Haqqani", new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 86, "Christ's Millennium starting by 2000.", false, "Timothy Dwight IV", new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 85, "The great tribulation would begin before 2000.", false, "James Gordon Lindsay", new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 84, "A nuclear holocaust would destroy Europe and Asia.", false, "Hon-Ming Chen", new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 83, "The world would end this year, maybe by nuclear devastation, asteroid impact, pole shift or other Earth changes.", false, "Charles Berlitz", new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 82, "A ball of fire will descend, destroying almost all of mankind, all vegetation and all forms of life.", false, "Philip Berg", new DateTime(1999, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1999, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 81, "This psychic, well known for predictions, predicted the end of the world on this date", false, "The Amazing Criswell", new DateTime(1999, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1999, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 91, "The Y2K bug would crash many computers at midnight on the 1st of January, causing malfuntions which lead to major catastrophies worldwide, causing society to stop functioning.", false, "Various", new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody, but there were some reported malfunctions with some technologies.", false },
                    { 53, "Armageddon occurs no later than 1977.", false, "William M. Branham", new DateTime(1977, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1977, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 52, "Armageddon.", false, "John Wroe", new DateTime(1977, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1977, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 51, "Armageddon where Brahma Kumari leaders will be purified whilst the rest of the world is killed by nuclear or civil wars, sinking all continents except India.", false, "Brahma Kumaris", new DateTime(1976, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1976, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 23, "The messiah will come within 6000 years of the creation of Adam, with the destruction of the world happening 1000 years later.", false, "Talmud, Orthodox Judaism", new DateTime(3239, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2239, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), null, true },
                    { 22, "An abjad interpretation of a hadith expects the world's end to occur in 2129.", false, "Said Nursî", new DateTime(2129, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2129, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), null, true },
                    { 21, "The world ends due to an asteroid colliding with Earth", false, "Messiah Foundation International", new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), null, true },
                    { 20, "Second coming of Jesus, with the rapture being in 2021 at the latest.", false, "F. Kenton Beshore", new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), null, true },
                    { 19, "Armageddon takes place.", false, "Jeane Dixon", new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), null, true },
                    { 18, "Jesus returns.", false, "Ronald Weinland", new DateTime(2019, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2019, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 17, "The rapture takes place and the world ends.", false, "David Meade", new DateTime(2018, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2018, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 16, "Nibiru would become visible in the sky and soon destroy the Earth.", false, "David Meade", new DateTime(2017, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2017, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 15, "The Blood Moon Prophecy. The tetrad (four lunar eclipses over two years) represents the beginning of the Messianic End Times.", true, "John Hagee & Mark Biltz", new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2014, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 14, "A storm would take place and fire destroys most life on land. Jesus returns to comfort those in distress.", false, "Grigori Rasputin", new DateTime(2013, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2013, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 24, "Predicts the world will end this year following reaseach of the Qu'ran.", false, "Rashad Khalifa", new DateTime(2280, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2280, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), null, true },
                    { 13, "The end of the Mesoamerican Long Count Calendar (Mayan Calendar). Predicted apocalypses include: the earth being destroyed by the asteroid Nibiru or some other interplanetary object, an alien invation or a supernova.", false, "Various", new DateTime(2012, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2012, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 11, "Revised date of Jesus' return following his failed 2011 prediction", false, "Ronald Weinland", new DateTime(2012, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2012, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", false },
                    { 10, "Rapture and end of the world following the spiritual judgment in May", false, "Harold Camping", new DateTime(2011, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2011, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", false },
                    { 9, "Jesus returns", false, "Ronald Weinland", new DateTime(2011, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2011, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", false },
                    { 8, "Spiritual judgment and devastating earthquakes", false, "Harold Camping", new DateTime(2011, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2011, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", false },
                    { 7, "Predicted the world would end.", false, "Hermetic Order of the Golden Dawn", new DateTime(2010, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2010, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", true },
                    { 6, "Apocalypse. 31 Adults and 4 children hid in a cave to escape it. Kuznetsov was not one of them.", true, "Pyotr Kuznetsov", new DateTime(2008, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2008, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "2 adults died in the cave. Kuznetsov was committed.", false },
                    { 5, "Predicted the Earth's destruction in his book The New Millennium.", false, "Pat Robertson", new DateTime(2007, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2007, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", false },
                    { 4, "World is destroyed by nuclear war beginning 12th of September 2006.", false, "House of Yahweh", new DateTime(2006, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2006, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", false },
                    { 3, "World is destroyed by nuclear war.", false, "Aum Shinrikyo", new DateTime(2003, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2003, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", false },
                    { 2, "Aliens in the Zeta Reticuli star system sent Lieder messages via a brain implant that a planet would enter the solar system and cause a pole shift.", false, "Nancy Lieder", new DateTime(2003, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2003, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody", false },
                    { 12, "The world's governments and economies collapse and followers of Luis de Jesús would undergo a transformation to be able to fly and walk through walls", false, "José Luis de Jesús", new DateTime(2012, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2012, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody. No reported supernatural abilities.", false },
                    { 25, "Jesus would return before the last of the 12 founding members of the church died. The last member died in 1901.", false, "Catholic Apostolic Church", new DateTime(1901, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1901, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 26, "Apocalypse", false, "Michael Paget Baxter", new DateTime(1908, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1908, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 27, "Halleys Comet would destroy all life on the planet. Comet Pills were sold to prevent against toxic gasses.", false, "Camille Flammarion", new DateTime(1910, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1910, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 50, "1975 is 6000 years since the creation of man and the end of the armageddon.", false, "Jehovah's Witnesses", new DateTime(1975, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1975, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 49, "The third and final revision of Armstrong's predicted Rapture.", false, "Herbert W. Armstrong", new DateTime(1975, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1975, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 48, "Doomsday heralded by Comet Kohoutek", true, "David Berg", new DateTime(1974, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1974, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 47, "The second revised date after his 1943 prediction failed.", false, "Herbert W. Armstrong", new DateTime(1972, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1972, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 46, "Helter Skelter, an apocalyptic race war, occurs.", false, "Charles Manson", new DateTime(1969, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1969, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody outside of the Manson Family murders.", false },
                    { 45, "The Second Coming of Christ occurs on this day", false, "George Williams", new DateTime(1969, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1969, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 44, "Nuclear holocaust would happen this year", false, "Jim Jones", new DateTime(1967, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1967, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 43, "Van Tassel channeled an alien named Ashtar who told him the third woe of the Apocalypse begins where the southeastern US is destroyed in a Soviet nuclear attack.", false, "George Van Tassel", new DateTime(1967, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1967, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 42, "A planetary alignment will bring destruction to the world.", false, "Jeane Dixon", new DateTime(1962, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1962, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody, but mass prayer meetings were held in India.", false },
                    { 41, "The second prophet of the Branch Davidians predicted the apocalypse foretold in the Book of Revelation occurrs on this date.", false, "Florence Houteff", new DateTime(1959, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1959, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody, but the Branch Davidians split into several subsects.", false },
                    { 40, "The world is destroyed by flooding", false, "Dorothy Martin", new DateTime(1954, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1954, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 39, "The destruction of all nations and the beginning of post-apocalyptic anarchy", false, "John Ballou Newbrough", new DateTime(1947, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1947, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 38, "Revised date of the previous rapture.", false, "Herbert W. Armstrong", new DateTime(1943, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1943, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 37, "Prediction of the end", false, "Jehovah's Witnesses", new DateTime(1941, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1941, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 36, "Rapture.", false, "Herbert W. Armstrong", new DateTime(1936, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1936, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 35, "The world is going to go puff and disappear", true, "Wilbur Glenn Voliva", new DateTime(1935, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1935, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 34, "The world is growing near apocalypse due to rampant immorality in Europe.", false, "Spencer Perceval", new DateTime(1926, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1926, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 33, "The angel Gabriel appeared before Rowen and told her that the world would end at midnight on this date.", false, "Margaret Rowen", new DateTime(1925, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1925, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 32, "God destroys churches and church members by the millions. Governments disappear with anarchy prevailing.", true, "International Bible Students Association", new DateTime(1920, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1920, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 31, "Christendom shall be cut off and glorification of the Little Flock (The Church) in the Spring of 1918", true, "International Bible Students Association", new DateTime(1918, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1918, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 30, "Predicted the Millennium would begin this year", false, "John Chilembwe", new DateTime(1915, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1915, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 29, "The close of the battle of the great day of God Almighty.", true, "Charles Taze Russell", new DateTime(1914, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1874, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 28, "Predicted the Second Coming, based off of the dimensions of the Great Pyramid of Giza.", false, "Charles Piazzi Smyth", new DateTime(1911, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1911, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true },
                    { 103, "God will arrive at Earth at 10am on this date in a flying saucer.", false, "Hon-Ming Chen", new DateTime(1998, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(1998, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", false },
                    { 104, "The Antichrist who came to power between 1300 and 1340 would perform the Last Judgment in 2000", false, "Peter Olivi", new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), "Nobody.", true }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Raptures");
        }
    }
}
