// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rapture.Repository;

namespace Rapture.Repository.Migrations
{
    [DbContext(typeof(RaptureContext))]
    partial class RaptureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.6.21352.1");

            modelBuilder.Entity("Rapture.Common.Models.RaptureModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Details");

                    b.Property<bool>("MonthOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("MonthOnly");

                    b.Property<string>("Predictor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Predictor");

                    b.Property<DateTime>("RaptureEndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndDate");

                    b.Property<DateTime>("RaptureStartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartDate");

                    b.Property<string>("WhoGotRaptured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("WhoGotRaptured");

                    b.Property<bool>("YearOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("YearOnly");

                    b.HasKey("Id");

                    b.ToTable("Raptures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Predicted the world would end this year",
                            MonthOnly = false,
                            Predictor = "Tynnetta Muhammad",
                            RaptureEndDate = new DateTime(2001, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2001, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 2,
                            Details = "Aliens in the Zeta Reticuli star system sent Lieder messages via a brain implant that a planet would enter the solar system and cause a pole shift.",
                            MonthOnly = false,
                            Predictor = "Nancy Lieder",
                            RaptureEndDate = new DateTime(2003, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2003, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 3,
                            Details = "World is destroyed by nuclear war.",
                            MonthOnly = false,
                            Predictor = "Aum Shinrikyo",
                            RaptureEndDate = new DateTime(2003, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2003, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 4,
                            Details = "World is destroyed by nuclear war beginning 12th of September 2006.",
                            MonthOnly = false,
                            Predictor = "House of Yahweh",
                            RaptureEndDate = new DateTime(2006, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2006, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 5,
                            Details = "Predicted the Earth's destruction in his book The New Millennium.",
                            MonthOnly = false,
                            Predictor = "Pat Robertson",
                            RaptureEndDate = new DateTime(2007, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2007, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 6,
                            Details = "Apocalypse. 31 Adults and 4 children hid in a cave to escape it. Kuznetsov was not one of them.",
                            MonthOnly = true,
                            Predictor = "Pyotr Kuznetsov",
                            RaptureEndDate = new DateTime(2008, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2008, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "2 adults died in the cave. Kuznetsov was committed.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 7,
                            Details = "Predicted the world would end.",
                            MonthOnly = false,
                            Predictor = "Hermetic Order of the Golden Dawn",
                            RaptureEndDate = new DateTime(2010, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2010, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 8,
                            Details = "Spiritual judgment and devastating earthquakes",
                            MonthOnly = false,
                            Predictor = "Harold Camping",
                            RaptureEndDate = new DateTime(2011, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2011, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 9,
                            Details = "Jesus returns",
                            MonthOnly = false,
                            Predictor = "Ronald Weinland",
                            RaptureEndDate = new DateTime(2011, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2011, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 10,
                            Details = "Rapture and end of the world following the spiritual judgment in May",
                            MonthOnly = false,
                            Predictor = "Harold Camping",
                            RaptureEndDate = new DateTime(2011, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2011, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 11,
                            Details = "Revised date of Jesus' return following his failed 2011 prediction",
                            MonthOnly = false,
                            Predictor = "Ronald Weinland",
                            RaptureEndDate = new DateTime(2012, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2012, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 12,
                            Details = "The world's governments and economies collapse and followers of Luis de Jesús would undergo a transformation to be able to fly and walk through walls",
                            MonthOnly = false,
                            Predictor = "José Luis de Jesús",
                            RaptureEndDate = new DateTime(2012, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2012, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody. No reported supernatural abilities.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 13,
                            Details = "The end of the Mesoamerican Long Count Calendar (Mayan Calendar). Predicted apocalypses include: the earth being destroyed by the asteroid Nibiru or some other interplanetary object, an alien invation or a supernova.",
                            MonthOnly = false,
                            Predictor = "Various",
                            RaptureEndDate = new DateTime(2012, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2012, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 14,
                            Details = "A storm would take place and fire destroys most life on land. Jesus returns to comfort those in distress.",
                            MonthOnly = false,
                            Predictor = "Grigori Rasputin",
                            RaptureEndDate = new DateTime(2013, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2013, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 15,
                            Details = "The Blood Moon Prophecy. The tetrad (four lunar eclipses over two years) represents the beginning of the Messianic End Times.",
                            MonthOnly = true,
                            Predictor = "John Hagee & Mark Biltz",
                            RaptureEndDate = new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2014, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 16,
                            Details = "Nibiru would become visible in the sky and soon destroy the Earth.",
                            MonthOnly = false,
                            Predictor = "David Meade",
                            RaptureEndDate = new DateTime(2017, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2017, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 17,
                            Details = "The rapture takes place and the world ends.",
                            MonthOnly = false,
                            Predictor = "David Meade",
                            RaptureEndDate = new DateTime(2018, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2018, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 18,
                            Details = "Jesus returns.",
                            MonthOnly = false,
                            Predictor = "Ronald Weinland",
                            RaptureEndDate = new DateTime(2019, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2019, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 19,
                            Details = "Armageddon takes place.",
                            MonthOnly = false,
                            Predictor = "Jeane Dixon",
                            RaptureEndDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearOnly = true
                        },
                        new
                        {
                            Id = 20,
                            Details = "Second coming of Jesus, with the rapture being in 2021 at the latest.",
                            MonthOnly = false,
                            Predictor = "F. Kenton Beshore",
                            RaptureEndDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearOnly = true
                        },
                        new
                        {
                            Id = 21,
                            Details = "The world ends due to an asteroid colliding with Earth",
                            MonthOnly = false,
                            Predictor = "Messiah Foundation International",
                            RaptureEndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearOnly = true
                        },
                        new
                        {
                            Id = 22,
                            Details = "An abjad interpretation of a hadith expects the world's end to occur in 2129.",
                            MonthOnly = false,
                            Predictor = "Said Nursî",
                            RaptureEndDate = new DateTime(2129, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2129, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearOnly = true
                        },
                        new
                        {
                            Id = 23,
                            Details = "The messiah will come within 6000 years of the creation of Adam, with the destruction of the world happening 1000 years later.",
                            MonthOnly = false,
                            Predictor = "Talmud, Orthodox Judaism",
                            RaptureEndDate = new DateTime(3239, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2239, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearOnly = true
                        },
                        new
                        {
                            Id = 24,
                            Details = "Predicts the world will end this year following reaseach of the Qu'ran.",
                            MonthOnly = false,
                            Predictor = "Rashad Khalifa",
                            RaptureEndDate = new DateTime(2280, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2280, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearOnly = true
                        },
                        new
                        {
                            Id = 25,
                            Details = "Jesus would return before the last of the 12 founding members of the church died. The last member died in 1901.",
                            MonthOnly = false,
                            Predictor = "Catholic Apostolic Church",
                            RaptureEndDate = new DateTime(1901, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1901, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 26,
                            Details = "Apocalypse",
                            MonthOnly = false,
                            Predictor = "Michael Paget Baxter",
                            RaptureEndDate = new DateTime(1908, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1908, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 27,
                            Details = "Halleys Comet would destroy all life on the planet. Comet Pills were sold to prevent against toxic gasses.",
                            MonthOnly = false,
                            Predictor = "Camille Flammarion",
                            RaptureEndDate = new DateTime(1910, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1910, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 28,
                            Details = "Predicted the Second Coming, based off of the dimensions of the Great Pyramid of Giza.",
                            MonthOnly = false,
                            Predictor = "Charles Piazzi Smyth",
                            RaptureEndDate = new DateTime(1911, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1911, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 29,
                            Details = "The close of the battle of the great day of God Almighty.",
                            MonthOnly = true,
                            Predictor = "Charles Taze Russell",
                            RaptureEndDate = new DateTime(1914, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1874, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 30,
                            Details = "Predicted the Millennium would begin this year",
                            MonthOnly = false,
                            Predictor = "John Chilembwe",
                            RaptureEndDate = new DateTime(1915, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1915, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 31,
                            Details = "Christendom shall be cut off and glorification of the Little Flock (The Church) in the Spring of 1918",
                            MonthOnly = true,
                            Predictor = "International Bible Students Association",
                            RaptureEndDate = new DateTime(1918, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1918, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 32,
                            Details = "God destroys churches and church members by the millions. Governments disappear with anarchy prevailing.",
                            MonthOnly = true,
                            Predictor = "International Bible Students Association",
                            RaptureEndDate = new DateTime(1920, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1920, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 33,
                            Details = "The angel Gabriel appeared before Rowen and told her that the world would end at midnight on this date.",
                            MonthOnly = false,
                            Predictor = "Margaret Rowen",
                            RaptureEndDate = new DateTime(1925, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1925, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 34,
                            Details = "The world is growing near apocalypse due to rampant immorality in Europe.",
                            MonthOnly = false,
                            Predictor = "Spencer Perceval",
                            RaptureEndDate = new DateTime(1926, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1926, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 35,
                            Details = "The world is going to go puff and disappear",
                            MonthOnly = true,
                            Predictor = "Wilbur Glenn Voliva",
                            RaptureEndDate = new DateTime(1935, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1935, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 36,
                            Details = "Rapture.",
                            MonthOnly = false,
                            Predictor = "Herbert W. Armstrong",
                            RaptureEndDate = new DateTime(1936, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1936, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 37,
                            Details = "Prediction of the end",
                            MonthOnly = false,
                            Predictor = "Jehovah's Witnesses",
                            RaptureEndDate = new DateTime(1941, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1941, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 38,
                            Details = "Revised date of the previous rapture.",
                            MonthOnly = false,
                            Predictor = "Herbert W. Armstrong",
                            RaptureEndDate = new DateTime(1943, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1943, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 39,
                            Details = "The destruction of all nations and the beginning of post-apocalyptic anarchy",
                            MonthOnly = false,
                            Predictor = "John Ballou Newbrough",
                            RaptureEndDate = new DateTime(1947, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1947, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 40,
                            Details = "The world is destroyed by flooding",
                            MonthOnly = false,
                            Predictor = "Dorothy Martin",
                            RaptureEndDate = new DateTime(1954, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1954, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 41,
                            Details = "The second prophet of the Branch Davidians predicted the apocalypse foretold in the Book of Revelation occurrs on this date.",
                            MonthOnly = false,
                            Predictor = "Florence Houteff",
                            RaptureEndDate = new DateTime(1959, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1959, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody, but the Branch Davidians split into several subsects.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 42,
                            Details = "A planetary alignment will bring destruction to the world.",
                            MonthOnly = false,
                            Predictor = "Jeane Dixon",
                            RaptureEndDate = new DateTime(1962, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1962, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody, but mass prayer meetings were held in India.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 43,
                            Details = "Van Tassel channeled an alien named Ashtar who told him the third woe of the Apocalypse begins where the southeastern US is destroyed in a Soviet nuclear attack.",
                            MonthOnly = false,
                            Predictor = "George Van Tassel",
                            RaptureEndDate = new DateTime(1967, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1967, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 44,
                            Details = "Nuclear holocaust would happen this year",
                            MonthOnly = false,
                            Predictor = "Jim Jones",
                            RaptureEndDate = new DateTime(1967, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1967, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 45,
                            Details = "The Second Coming of Christ occurs on this day",
                            MonthOnly = false,
                            Predictor = "George Williams",
                            RaptureEndDate = new DateTime(1969, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1969, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 46,
                            Details = "Helter Skelter, an apocalyptic race war, occurs.",
                            MonthOnly = false,
                            Predictor = "Charles Manson",
                            RaptureEndDate = new DateTime(1969, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1969, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody outside of the Manson Family murders.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 47,
                            Details = "The second revised date after his 1943 prediction failed.",
                            MonthOnly = false,
                            Predictor = "Herbert W. Armstrong",
                            RaptureEndDate = new DateTime(1972, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1972, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 48,
                            Details = "Doomsday heralded by Comet Kohoutek",
                            MonthOnly = true,
                            Predictor = "David Berg",
                            RaptureEndDate = new DateTime(1974, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1974, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 49,
                            Details = "The third and final revision of Armstrong's predicted Rapture.",
                            MonthOnly = false,
                            Predictor = "Herbert W. Armstrong",
                            RaptureEndDate = new DateTime(1975, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1975, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 50,
                            Details = "1975 is 6000 years since the creation of man and the end of the armageddon.",
                            MonthOnly = false,
                            Predictor = "Jehovah's Witnesses",
                            RaptureEndDate = new DateTime(1975, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1975, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 51,
                            Details = "Armageddon where Brahma Kumari leaders will be purified whilst the rest of the world is killed by nuclear or civil wars, sinking all continents except India.",
                            MonthOnly = false,
                            Predictor = "Brahma Kumaris",
                            RaptureEndDate = new DateTime(1976, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1976, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 52,
                            Details = "Armageddon.",
                            MonthOnly = false,
                            Predictor = "John Wroe",
                            RaptureEndDate = new DateTime(1977, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1977, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 53,
                            Details = "Armageddon occurs no later than 1977.",
                            MonthOnly = false,
                            Predictor = "William M. Branham",
                            RaptureEndDate = new DateTime(1977, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1977, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 54,
                            Details = "Led a commune into the Quebec wilderness to form a new society during God's 1000 year reign followed by Armageddon.",
                            MonthOnly = false,
                            Predictor = "Roch Thériault",
                            RaptureEndDate = new DateTime(1979, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1979, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 55,
                            Details = "Nuclear disaster, followed by two decades of conflict culminating in God's Kingdom being established on Earth.",
                            MonthOnly = false,
                            Predictor = "Leland Jensen",
                            RaptureEndDate = new DateTime(1980, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1980, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 56,
                            Details = "The generation of 1948 is the last generation and the world ends in 1981.",
                            MonthOnly = false,
                            Predictor = "Chuck Smith",
                            RaptureEndDate = new DateTime(1981, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1981, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 57,
                            Details = "Believed the gravitational force of the aligned planets would cause a number of catastrophes, including earthquakes across the San Andreas Fault.",
                            MonthOnly = false,
                            Predictor = "John Gribbin, Stephen Plagemann",
                            RaptureEndDate = new DateTime(1982, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1982, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 58,
                            Details = "Declared \"Christ is now here!\" in newspaper advertisements and claimed he would make himself known \"within the next two months \"",
                            MonthOnly = true,
                            Predictor = "Tara Centers",
                            RaptureEndDate = new DateTime(1982, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1982, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 59,
                            Details = "Placed advertisements in the Los Angeles Times stating that the second coming would occur in June with the Maitreya (World Teacher) announcing it on worldwide TV.",
                            MonthOnly = false,
                            Predictor = "Benjamin Creme",
                            RaptureEndDate = new DateTime(1982, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1982, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 60,
                            Details = "Predicted the world would end this year on his 700 Club TV programme.",
                            MonthOnly = false,
                            Predictor = "Pat Robertson",
                            RaptureEndDate = new DateTime(1982, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1982, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 61,
                            Details = "Predicted the world ends in 1985.",
                            MonthOnly = false,
                            Predictor = "Lester Sumrall",
                            RaptureEndDate = new DateTime(1985, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1985, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 62,
                            Details = "Predicted that Halley's Comet would be pulled into Earth's orbit.",
                            MonthOnly = false,
                            Predictor = "Leland Jensen",
                            RaptureEndDate = new DateTime(1986, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1986, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 63,
                            Details = "Rapture of the Christian Church.",
                            MonthOnly = false,
                            Predictor = "Edgar C. Whisenant",
                            RaptureEndDate = new DateTime(1988, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1988, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 64,
                            Details = "Whisenant's revised prediction of the rapture of the Christian Church, following the failed September prediction.",
                            MonthOnly = false,
                            Predictor = "Edgar C. Whisenant",
                            RaptureEndDate = new DateTime(1988, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1988, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 65,
                            Details = "A nuclear war starts on this day and lasts for 12 years.",
                            MonthOnly = false,
                            Predictor = "Elizabeth Clare Prophet",
                            RaptureEndDate = new DateTime(1990, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1990, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 66,
                            Details = "The Messiah would arrive at the start of the Jewish New Year",
                            MonthOnly = false,
                            Predictor = "Menachem Mendel Schneerson",
                            RaptureEndDate = new DateTime(1991, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1991, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 67,
                            Details = "The Gulf War would be the War of Armageddon which is the final war",
                            MonthOnly = false,
                            Predictor = "Louis Farrakhan",
                            RaptureEndDate = new DateTime(1991, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1991, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 68,
                            Details = "The rapture begins",
                            MonthOnly = false,
                            Predictor = "Rollen Stewart",
                            RaptureEndDate = new DateTime(1992, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1992, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 69,
                            Details = "The rapture occurs on this day",
                            MonthOnly = false,
                            Predictor = "Lee Jang Rim",
                            RaptureEndDate = new DateTime(1992, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1992, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 70,
                            Details = "The Second Coming takes place this year",
                            MonthOnly = false,
                            Predictor = "David Berg",
                            RaptureEndDate = new DateTime(1993, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1993, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 71,
                            Details = "New York City would be destroyed by a nuclear bomb on the 23rd of March 1994, with the Battle of Armageddon taking place on the 2nd of May 1994.",
                            MonthOnly = false,
                            Predictor = "Neal Chase",
                            RaptureEndDate = new DateTime(1994, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1994, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 72,
                            Details = "Camping predicted the rapture would take place.",
                            MonthOnly = false,
                            Predictor = "Harold Camping",
                            RaptureEndDate = new DateTime(1994, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1994, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 73,
                            Details = "Camping's next rapture predicting, following the failure of his first.",
                            MonthOnly = false,
                            Predictor = "Harold Camping",
                            RaptureEndDate = new DateTime(1994, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1994, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 74,
                            Details = "Camping's third rapture prediction, following the failure of his previous two.",
                            MonthOnly = false,
                            Predictor = "Harold Camping",
                            RaptureEndDate = new DateTime(1994, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1994, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 75,
                            Details = "Camping's fourth rapture prediction, following the failure of his previous three.",
                            MonthOnly = false,
                            Predictor = "Harold Camping",
                            RaptureEndDate = new DateTime(1995, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1995, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 76,
                            Details = "The world ends with the arrival of 16 million space ships and a host of angels.",
                            MonthOnly = false,
                            Predictor = "Sheldan Nidle",
                            RaptureEndDate = new DateTime(1996, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1996, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 77,
                            Details = "A spacecraft was trailing the Hale-Bopp comet and suicide was the only way to evacuate Earth the souls could board the spacecraft and be taken to a level of exitence above human.",
                            MonthOnly = false,
                            Predictor = "Marshall Applewhite",
                            RaptureEndDate = new DateTime(1997, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1997, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "38 of Applewhite's followers commited suicide. It's unknown as to whether or not their souls reached the spacecraft.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 78,
                            Details = "This date is 6000 years since the creation, and therefore the end of the world.",
                            MonthOnly = false,
                            Predictor = "James Ussher",
                            RaptureEndDate = new DateTime(1997, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1997, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 79,
                            Details = "God will arrive at Earth at 10am on this date in a flying saucer.",
                            MonthOnly = false,
                            Predictor = "Hon-Ming Chen",
                            RaptureEndDate = new DateTime(1998, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1998, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 80,
                            Details = "A King of Terror would come from the sky in \"1999 and seven months\".",
                            MonthOnly = true,
                            Predictor = "Nostradamus",
                            RaptureEndDate = new DateTime(1999, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1999, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 81,
                            Details = "This psychic, well known for predictions, predicted the end of the world on this date",
                            MonthOnly = false,
                            Predictor = "The Amazing Criswell",
                            RaptureEndDate = new DateTime(1999, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1999, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 82,
                            Details = "A ball of fire will descend, destroying almost all of mankind, all vegetation and all forms of life.",
                            MonthOnly = false,
                            Predictor = "Philip Berg",
                            RaptureEndDate = new DateTime(1999, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1999, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 83,
                            Details = "The world would end this year, maybe by nuclear devastation, asteroid impact, pole shift or other Earth changes.",
                            MonthOnly = false,
                            Predictor = "Charles Berlitz",
                            RaptureEndDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 84,
                            Details = "A nuclear holocaust would destroy Europe and Asia.",
                            MonthOnly = false,
                            Predictor = "Hon-Ming Chen",
                            RaptureEndDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 85,
                            Details = "The great tribulation would begin before 2000.",
                            MonthOnly = false,
                            Predictor = "James Gordon Lindsay",
                            RaptureEndDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 86,
                            Details = "Christ's Millennium starting by 2000.",
                            MonthOnly = false,
                            Predictor = "Timothy Dwight IV",
                            RaptureEndDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 87,
                            Details = "The last judgment would occur before 2000.",
                            MonthOnly = false,
                            Predictor = "Nazim Al-Haqqani",
                            RaptureEndDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 88,
                            Details = "Apocalypse",
                            MonthOnly = false,
                            Predictor = "Movement for the Restoration of the Ten Commandments of God",
                            RaptureEndDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody, but 778 followers of this movement died in a fire and a series of poisonings and killings, either as a form of group suicide or orchestrated mass murder by the group leaders after the failed prediction.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 89,
                            Details = "God pours his judgment upon the world",
                            MonthOnly = false,
                            Predictor = "Jerry Falwell",
                            RaptureEndDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 90,
                            Details = "The Y2K bug would trigger global economic chaos, causing the Antichrist to rise to power. They changed their minds about this prediction as the date drew closer.",
                            MonthOnly = false,
                            Predictor = "Tim LaHaye & Jerry B. Jenkins",
                            RaptureEndDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 91,
                            Details = "The Y2K bug would crash many computers at midnight on the 1st of January, causing malfuntions which lead to major catastrophies worldwide, causing society to stop functioning.",
                            MonthOnly = false,
                            Predictor = "Various",
                            RaptureEndDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody, but there were some reported malfunctions with some technologies.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 92,
                            Details = "The Second Coming of Christ occurs on this day",
                            MonthOnly = false,
                            Predictor = "James Harmston",
                            RaptureEndDate = new DateTime(2000, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 93,
                            Details = "The planetary lineup would cause a \"star holocaust\", pulling all the planets into the sun.",
                            MonthOnly = false,
                            Predictor = "Nuwaubian Nation",
                            RaptureEndDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 94,
                            Details = "The Earth's axis would shift and the Antichrist would reveal himself",
                            MonthOnly = false,
                            Predictor = "Ruth Montgomery",
                            RaptureEndDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 95,
                            Details = "The Second Coming would occur in the year 2000",
                            MonthOnly = false,
                            Predictor = "Edgar Cayce",
                            RaptureEndDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 96,
                            Details = "The Kingdom of Heaven would be established in 2000",
                            MonthOnly = false,
                            Predictor = "Sun Myung Moon",
                            RaptureEndDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 97,
                            Details = "Predicted the end of the world in his book \"The End: Why Jesus Could Return by A.D. 2000\"",
                            MonthOnly = false,
                            Predictor = "Ed Dobson",
                            RaptureEndDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 98,
                            Details = "Predicted the end of the world in his book \"I Predict 2000\"",
                            MonthOnly = false,
                            Predictor = "Lester Sumrall",
                            RaptureEndDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 99,
                            Details = "Christ's 1000 year reign would begin in the year 2000",
                            MonthOnly = false,
                            Predictor = "Jonathan Edwards",
                            RaptureEndDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        },
                        new
                        {
                            Id = 100,
                            Details = "Armageddon would heppen unless 144,000 people gathered in specifc places on Earth and meditated at the same time, which became known as Harmonic Convergence.",
                            MonthOnly = false,
                            Predictor = "José Argüelles",
                            RaptureEndDate = new DateTime(1987, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1987, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 101,
                            Details = "Whisenant's revised prediction of the rapture of the Christian Church, following failure of his two previous predictions.",
                            MonthOnly = false,
                            Predictor = "Edgar C. Whisenant",
                            RaptureEndDate = new DateTime(1989, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1989, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 102,
                            Details = "The birth date of the Antichrist and the end of the universe.",
                            MonthOnly = false,
                            Predictor = "Aggai",
                            RaptureEndDate = new DateTime(1997, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1997, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 103,
                            Details = "God will arrive at Earth at 10am on this date in a flying saucer.",
                            MonthOnly = false,
                            Predictor = "Hon-Ming Chen",
                            RaptureEndDate = new DateTime(1998, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(1998, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = false
                        },
                        new
                        {
                            Id = 104,
                            Details = "The Antichrist who came to power between 1300 and 1340 would perform the Last Judgment in 2000",
                            MonthOnly = false,
                            Predictor = "Peter Olivi",
                            RaptureEndDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RaptureStartDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoGotRaptured = "Nobody.",
                            YearOnly = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
